spring:
  application:
    name: jeecg-system
  profiles:
    active: prod

config:
#  jenkins_username: admin
#  jenkins_username_pwd: admin
#  jenkins_token: 11565f73f17dfbabf9a24991540f18d761
#  jenkins_url: 192.168.48.2:8080/

  jenkins_username: admin
  jenkins_username_pwd: admin
  jenkins_token: 11ce76a40837300af8681ca76b958ccdac
  jenkins_url: 192.168.49.21:8083/

  mail:
    host: smtp.263.net
    username: droi_devops_service@droi.com
    password: Droi*#2021
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true