spring:
  application:
    name: jeecg-system
  profiles:
    active: dev

config:
  jenkins_username: admin
  jenkins_username_pwd: admin
  jenkins_token: 1150d1c0e2b2cc9062e852dfac6f352d9f
  jenkins_url: 192.168.151.238:8080/