spring:
  application:
    name: jeecg-system
  profiles:
    active: dev

config:
  jenkins_username: admin
  jenkins_username_pwd: admin
  jenkins_token: 11396481296612726c41b2c9dcacc19688
  jenkins_url: 192.168.151.14:8080/